FROM ubuntu:21.04

ENV EMAIL=bot@netdata.cloud
ENV FULLNAME="Netdata Builder"
ENV VERSION=0.1

# This is needed to keep package installs from prompting about configuration.
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends autoconf \
                       autoconf-archive \
                       autogen \
                       automake \
                       build-essential \
                       ca-certificates \
                       cmake \
                       curl \
                       dh-autoreconf \
                       dh-make \
                       dh-systemd \
                       systemd \
                       dpkg-dev \
                       g++ \
                       gcc \
                       git-core \
                       git-buildpackage \
                       libcups2-dev \
                       libdistro-info-perl \
                       libelf-dev \
                       libipmimonitoring-dev \
                       libjson-c-dev \
                       libjudy-dev \
                       liblz4-dev \
                       libmnl-dev \
                       libnetfilter-acct-dev \
                       libprotobuf-dev \
                       libprotoc-dev \
                       libsnappy-dev \
                       libssl-dev \
                       libtool \
                       libuv1-dev \
                       make \
                       pkg-config \
                       protobuf-compiler \
                       uuid-dev \
                       wget \
                       zlib1g-dev && \
    apt-get clean && \
    c_rehash && \
    rm -rf /var/lib/apt/lists/*

COPY package-builders/entrypoint.sh /entrypoint.sh
COPY package-builders/debian-build.sh /build.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/build.sh"]
