FROM opensuse/leap:15.0

ARG VERSION=0.1

ENV VERSION=$VERSION

COPY package-builders/suse-build.sh /build.sh

RUN zypper update -y && \
    zypper install -y autoconf \
                      autoconf-archive \
                      autogen \
                      automake \
                      cups \
                      cups-devel \
                      curl \
                      diffutils \
                      freeipmi-devel \
                      gcc \
                      gcc-c++ \
                      git-core \
                      json-glib-devel \
                      judy-devel \
                      liblz4-devel \
                      libmnl0 \
                      libmnl-devel \
                      libnetfilter_acct1 \
                      libnetfilter_acct-devel \
                      libopenssl-devel \
                      libuv-devel \
                      libuuid-devel \
                      make \
                      patch \
                      pkg-config \
                      protobuf-c \
                      protobuf-devel \
                      rpm-build \
                      rpm-devel \
                      rpmdevtools \
                      snappy-devel \
                      tar \
                      wget && \
    zypper clean && \
    rm -rf /var/cache/zypp/*/* && \
    mkdir -p /usr/src/packages/BUILD /usr/src/packages/RPMS /usr/src/packages/SOURCES /usr/src/packages/SPECS /usr/src/packages/SRPMS
