FROM ubuntu:22.10

LABEL org.opencontainers.image.authors="Netdatabot <bot@netdata.cloud>"
LABEL org.opencontainers.image.source="https://github.com/netdata/helper-images"
LABEL org.opencontainers.image.title="Netdata Package Builder for Ubuntu 22.10"
LABEL org.opencontainers.image.description="Package builder image for Netdata official DEB packages for Ubuntu 22.10"
LABEL org.opencontainers.image.vendor="Netdata Inc."

ENV EMAIL=bot@netdata.cloud
ENV FULLNAME="Netdata Builder"
ENV VERSION=0.1

# This is needed to keep package installs from prompting about configuration.
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends autoconf \
                       autoconf-archive \
                       autogen \
                       automake \
                       bison \
                       build-essential \
                       ca-certificates \
                       cmake \
                       curl \
                       dh-autoreconf \
                       dh-make \
                       dpkg-dev \
                       flex \
                       g++ \
                       gcc \
                       git-buildpackage \
                       git-core \
                       golang \
                       libatomic1 \
                       libcups2-dev \
                       libdistro-info-perl \
                       libelf-dev \
                       libipmimonitoring-dev \
                       libjson-c-dev \
                       libyaml-dev \
                       libjudy-dev \
                       liblz4-dev \
                       libmnl-dev \
                       libnetfilter-acct-dev \
                       libprotobuf-dev \
                       libprotoc-dev \
                       libsnappy-dev \
                       libssl-dev \
                       libtool \
                       libuv1-dev \
                       make \
                       pkg-config \
                       protobuf-compiler \
                       systemd \
                       uuid-dev \
                       wget \
                       zlib1g-dev && \
    apt-get clean && \
    c_rehash && \
    rm -rf /var/lib/apt/lists/*

COPY package-builders/entrypoint.sh /entrypoint.sh
COPY package-builders/debian-build.sh /build.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/build.sh"]
