FROM opensuse/leap:15.0

RUN zypper update -y

RUN zypper install -y wget \
                      curl \
                      cups \
                      freeipmi-devel \
                      libmnl-devel \
                      tar \
                      sudo \
                      libnetfilter_acct1 \
                      gcc \
                      make \
                      automake \
                      autoconf \
                      liblz4-devel \
                      cups-devel \
                      libuuid-devel \
                      judy-devel \
                      libmnl0 \
                      pkgconfig \
                      git \
                      libopenssl-devel \
                      libnetfilter_acct-devel
