FROM alpine:3.15

RUN apk add --no-cache \
    alpine-sdk \
    autoconf \
    automake \
    bash \
    binutils \
    cmake \
    curl \
    elfutils-dev \
    gcc \
    git \
    gnutls-dev \
    gzip \
    libelf-static \
    libmnl-dev \
    libnetfilter_acct-dev \
    libtool \
    libuv-dev \
    libuv-static \
    lz4-dev \
    lz4-static \
    make \
    ncurses \
    netcat-openbsd \
    openssh \
    pkgconfig \
    protobuf-dev \
    snappy-dev \
    snappy-static \
    util-linux-dev \
    wget \
    xz \
    zlib-dev \
    zlib-static
