name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build and Test Builder/Base and OS Lifecycle tests for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [i386, armhf, aarch64, amd64]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run build.sh
      run: |
        ./.github/build.sh
      env:
        - ARCH=${{ matrix.arch }}
      shell: bash
