---
# Builds all OS Docker Images used for OS testing
name: OS
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          - alpine
          - archlinux
          - centos7
          - debian_bullseye
          - debian_buster
          - debian_jessie
          - debian_stretch
          - fedora29
          - fedora30
          - fedora31
          - opensuse15.0
          - opensuse15.1
          - opensuse42.3
          - opensuse_tumbleweed
          - ubuntu1604
          - ubuntu1804
          - ubuntu1904
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker build -f ./oses/Dockerfile.${{ matrix.os}} -t netdata/os-test:${{ matrix.os }} ./
