---
# Builds all OS Docker Images used for OS testing
name: OS
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  build:
    name: Build
    if: github.event_name == 'pull_request' || github.event_name == 'push' || (github.event_name == 'schedule' && github.repository == 'netdata/helper-images')
    strategy:
      matrix:
        os:
          - alpine
          - archlinux
          - centos7
          - debian_bullseye
          - debian_buster
          - debian_jessie
          - debian_stretch
          - fedora29
          - fedora30
          - fedora31
          - opensuse15.0
          - opensuse15.1
          - opensuse42.3
          - opensuse_tumbleweed
          - ubuntu1604
          - ubuntu1804
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check if we should push images
        if: (github.event_name == 'schedule' || github.event_name == 'push')
        run: echo 'PUSH_IMAGES=true' >> $GITHUB_ENV
      - name: Check if we should push images
        if: github.event_name == 'pull_request'
        run: echo 'PUSH_IMAGES=false' >> $GITHUB_ENV
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Hub Login
        if: env.PUSH_IMAGES == 'true'
        uses: docker/login-action@v1
        with:
          username: netdatabot
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: ${{ env.PUSH_IMAGES }}
          file: ./oses/Dockerfile.${{ matrix.os }}
          tags: netdata/os-test:${{ matrix.os }}
